<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>DHR-{{ $inspection->id }} | Cosmas Damian</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Courier New',monospace;font-size:10px;color:#000;background:#fff;padding:20px;}
.page{max-width:760px;margin:0 auto;}
.header{border:2px solid #000;padding:16px;margin-bottom:12px;}
.header-top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px;}
.logo{font-size:18px;font-weight:700;letter-spacing:0.1em;}
.logo span{color:#555;}
.dhr-title{font-size:13px;font-weight:700;letter-spacing:0.05em;text-align:right;}
.dhr-num{font-size:11px;color:#555;}
.regulatory{font-size:8px;color:#555;border-top:1px solid #ccc;padding-top:6px;margin-top:6px;}
.section{border:1px solid #000;margin-bottom:8px;}
.section-title{background:#000;color:#fff;padding:5px 10px;font-size:9px;font-weight:700;letter-spacing:0.12em;}
.section-body{padding:10px;}
.grid-2{display:grid;grid-template-columns:1fr 1fr;gap:8px;}
.grid-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;}
.field{margin-bottom:6px;}
.field-label{font-size:8px;font-weight:700;letter-spacing:0.1em;color:#555;text-transform:uppercase;margin-bottom:2px;}
.field-value{font-size:10px;font-weight:600;border-bottom:1px solid #000;padding-bottom:2px;min-height:16px;}
.verdict-pass{color:#006400;font-size:14px;font-weight:700;}
.verdict-fail{color:#8B0000;font-size:14px;font-weight:700;}
.verdict-flagged{color:#8B6914;font-size:14px;font-weight:700;}
.risk-critical{color:#8B0000;}
.risk-high{color:#8B3A00;}
.risk-medium{color:#8B6914;}
.risk-low{color:#006400;}
.agent-step{border-left:2px solid #000;padding:4px 8px;margin-bottom:4px;font-size:9px;}
.step-label{font-weight:700;font-size:8px;letter-spacing:0.08em;color:#555;}
.reasoning{font-size:9px;line-height:1.5;white-space:pre-wrap;border:1px solid #ccc;padding:8px;max-height:200px;overflow:hidden;}
.signature-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;margin-top:8px;}
.sig-block{border-top:1px solid #000;padding-top:4px;}
.sig-label{font-size:8px;color:#555;}
.footer{text-align:center;font-size:8px;color:#555;margin-top:12px;border-top:1px solid #ccc;padding-top:8px;}
@media print{
  body{padding:0;}
  .no-print{display:none !important;}
  .page{max-width:100%;}
  @page{margin:15mm;size:A4;}
}
</style>
</head>
<body>
<div class="page">

  {{-- Print / Back buttons --}}
  <div class="no-print" style="display:flex;gap:8px;margin-bottom:12px;">
    <button onclick="window.print()"
      style="background:#000;color:#fff;font-family:'Courier New',monospace;font-size:10px;font-weight:700;
             letter-spacing:0.1em;padding:8px 20px;border:none;cursor:pointer;">
      ⬇ DOWNLOAD / PRINT PDF
    </button>
    <a href="{{ route('inspections.results', $inspection->id) }}"
      style="background:#fff;color:#000;font-family:'Courier New',monospace;font-size:10px;
             padding:8px 20px;border:1px solid #000;text-decoration:none;">
      ← BACK TO REPORT
    </a>
  </div>

  {{-- Document Header --}}
  <div class="header">
    <div class="header-top">
      <div>
        <div class="logo">COSMAS·<span>DAMIAN</span></div>
        <div style="font-size:8px;color:#555;margin-top:2px;">AI-Powered Surgical Instrument QC System</div>
      </div>
      <div style="text-align:right;">
        <div class="dhr-title">DEVICE HISTORY RECORD</div>
        <div class="dhr-num">DHR-{{ str_pad($inspection->id, 6, '0', STR_PAD_LEFT) }}</div>
        <div style="font-size:8px;color:#555;">{{ $inspection->created_at->format('Y-m-d H:i:s') }} UTC</div>
      </div>
    </div>
    <div class="regulatory">
      Per 21 CFR Part 820.184 — Device History Record requirement &nbsp;|&nbsp;
      21 CFR Part 11 — Electronic Records &nbsp;|&nbsp;
      ISO 13485:2016 Section 7.5.1 — Production Controls &nbsp;|&nbsp;
      Generated by COSMAS DAMIAN v1.0
    </div>
  </div>

  {{-- Device Identification --}}
  <div class="section">
    <div class="section-title">[ 1 ] DEVICE IDENTIFICATION — 21 CFR 820.184(a)</div>
    <div class="section-body">
      <div class="grid-3">
        <div class="field"><div class="field-label">Instrument ID</div><div class="field-value">{{ $inspection->instrument_id ?: 'N/A' }}</div></div>
        <div class="field"><div class="field-label">Instrument Class</div><div class="field-value">{{ ucfirst($inspection->instrument_class ?: 'Unknown') }}</div></div>
        <div class="field"><div class="field-label">DHR Number</div><div class="field-value">DHR-{{ str_pad($inspection->id, 6, '0', STR_PAD_LEFT) }}</div></div>
      </div>
      <div class="grid-3">
        <div class="field"><div class="field-label">Operator ID</div><div class="field-value">{{ $inspection->operator_id ?: 'N/A' }}</div></div>
        <div class="field"><div class="field-label">Inspector</div><div class="field-value">{{ $inspection->user->name ?? 'Unknown' }}</div></div>
        <div class="field"><div class="field-label">Date of Inspection</div><div class="field-value">{{ $inspection->created_at->format('Y-m-d') }}</div></div>
      </div>
    </div>
  </div>

  {{-- QC Verdict --}}
  <div class="section">
    <div class="section-title">[ 2 ] ACCEPTANCE RECORDS — 21 CFR 820.184(e)</div>
    <div class="section-body">
      <div class="grid-3">
        <div class="field">
          <div class="field-label">Final Verdict</div>
          <div class="field-value @php echo 'verdict-' . strtolower($inspection->pass_fail ?? 'fail') @endphp">
            {{ strtoupper($inspection->pass_fail ?? 'FAIL') }}
          </div>
        </div>
        <div class="field">
          <div class="field-label">Risk Level</div>
          <div class="field-value risk-{{ strtolower($inspection->risk_level ?? 'unknown') }}">
            {{ strtoupper($inspection->risk_level ?? 'UNKNOWN') }}
          </div>
        </div>
        <div class="field">
          <div class="field-label">Composite Risk Score (CRS)</div>
          <div class="field-value">{{ $inspection->composite_risk_score ? number_format($inspection->composite_risk_score, 1) : 'N/A' }}</div>
        </div>
      </div>
      <div class="grid-3">
        <div class="field"><div class="field-label">Defect Type</div><div class="field-value">{{ ucfirst($inspection->defect_type ?: 'None detected') }}</div></div>
        <div class="field"><div class="field-label">AI Confidence</div><div class="field-value">{{ $inspection->confidence ? $inspection->confidence . '%' : 'N/A' }}</div></div>
        <div class="field"><div class="field-label">YOLO Detections</div><div class="field-value">{{ $inspection->yolo_count ?? 0 }} detection(s)</div></div>
      </div>
      @if($inspection->recommended_action)
      <div class="field" style="margin-top:4px;">
        <div class="field-label">Recommended Action</div>
        <div class="field-value">{{ $inspection->recommended_action }}</div>
      </div>
      @endif
    </div>
  </div>

  {{-- Regulatory Context --}}
  <div class="section">
    <div class="section-title">[ 3 ] REGULATORY CONTEXT — 21 CFR 820.184(f)</div>
    <div class="section-body">
      <div class="field">
        <div class="field-label">Applicable Standard</div>
        <div class="field-value">{{ $inspection->regulatory_note ?: 'FDA 21 CFR Part 820 — Quality System Regulation' }}</div>
      </div>
      <div class="grid-2" style="margin-top:6px;">
        <div class="field"><div class="field-label">QMS Reference</div><div class="field-value">FDA 21 CFR Part 820.184</div></div>
        <div class="field"><div class="field-label">Electronic Record</div><div class="field-value">21 CFR Part 11 Compliant</div></div>
      </div>
    </div>
  </div>

  {{-- AI Agent Reasoning --}}
  <div class="section">
    <div class="section-title">[ 4 ] AI SYSTEM ANALYSIS — AGENTIC TOOL-USE LOG</div>
    <div class="section-body">
      @php $steps = $inspection->agent_steps_decoded ?? []; @endphp
      @if(!empty($steps))
        @foreach(array_slice($steps, 0, 5) as $i => $step)
        <div class="agent-step">
          <div class="step-label">STEP {{ $i+1 }}: {{ strtoupper($step['tool'] ?? 'UNKNOWN') }}</div>
          <div>{{ Str::limit(json_encode($step['result'] ?? ''), 200) }}</div>
        </div>
        @endforeach
      @else
        <div class="reasoning">{{ Str::limit($inspection->claude_reasoning ?? 'No reasoning recorded.', 800) }}</div>
      @endif
      <div style="font-size:8px;color:#555;margin-top:6px;">
        Model: Claude claude-sonnet-4-6 | Pipeline: YOLOv8n (instrument) + YOLOv8s (defect) | Latency: {{ $inspection->inference_ms ?? 'N/A' }}ms
      </div>
    </div>
  </div>

  {{-- Signatures --}}
  <div class="section">
    <div class="section-title">[ 5 ] AUTHORIZATION & SIGNATURES — 21 CFR 820.184(g)</div>
    <div class="section-body">
      <div style="font-size:8px;color:#555;margin-bottom:10px;">
        This Device History Record was generated electronically per 21 CFR Part 11. The AI inspection result is a
        recommendation only — final disposition requires authorized human QC sign-off per 21 CFR 820.80.
      </div>
      <div class="signature-grid">
        <div class="sig-block">
          <div style="height:32px;"></div>
          <div class="sig-label">QC Inspector Signature</div>
          <div class="sig-label">Date: _______________</div>
        </div>
        <div class="sig-block">
          <div style="height:32px;"></div>
          <div class="sig-label">QC Manager Review</div>
          <div class="sig-label">Date: _______________</div>
        </div>
        <div class="sig-block">
          <div style="height:32px;"></div>
          <div class="sig-label">Disposition Authority</div>
          <div class="sig-label">Date: _______________</div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
    COSMAS DAMIAN AI-Powered QC System &nbsp;|&nbsp;
    DHR-{{ str_pad($inspection->id, 6, '0', STR_PAD_LEFT) }} &nbsp;|&nbsp;
    Generated: {{ now()->format('Y-m-d H:i:s') }} UTC &nbsp;|&nbsp;
    Retain per 21 CFR 820.184 for device expected lifetime or minimum 2 years &nbsp;|&nbsp;
    cosmas-damian.duckdns.org
  </div>

</div>
</body>
</html>
